services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_CONTEXT_LENGTH=32768
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

volumes:
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/.ollama
